# Generated by Django 4.0.2 on 2022-04-04 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='lock',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 20, 10, 14, 647356)),
        ),
        migrations.CreateModel(
            name='ProductViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfoodapp.vendorproduct')),
            ],
        ),
    ]
