# Generated by Django 4.0.2 on 2022-04-05 08:07

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmfoodapp', '0003_alter_registermodel_lock_vendorblogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorblogs',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorblogs',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='lock',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 5, 7, 19, 753457)),
        ),
        migrations.AlterField(
            model_name='vendorblogs',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vendorblogs',
            name='title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
