# Generated by Django 4.0.2 on 2022-04-05 08:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmfoodapp', '0004_vendorblogs_date_created_vendorblogs_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='lock',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 5, 55, 17, 722060)),
        ),
        migrations.CreateModel(
            name='CostManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('coster', models.CharField(max_length=200)),
                ('expense', models.DecimalField(decimal_places=10, max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmfoodapp.registermodel')),
            ],
        ),
    ]
